[versions]
# https://mvnrepository.com/artifact/com.android.tools.build/gradle
android = "8.13.2"
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.3.0"
# https://github.com/Kotlin/kotlinx-kover/releases
kover = "0.9.6"
# https://github.com/vanniktech/gradle-maven-publish-plugin/releases
maven-publish = "0.35.0"

# https://developer.android.com/jetpack/androidx/releases/arch-core
androidx-arch-core = "2.2.0"
# https://developer.android.com/jetpack/androidx/releases/fragment#declaring_dependencies
androidx-fragment = "1.8.9"
# https://developer.android.com/jetpack/androidx/releases/lifecycle#declaring_dependencies
androidx-lifecycle = "2.10.0"
# https://developer.android.com/jetpack/androidx/releases/test#declaring_dependencies
androidx-test-runner = "1.7.0"
androidx-test-junit = "1.3.0"

# https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-coroutines = "1.10.2"

# https://github.com/junit-team/junit4/releases
junit4 = "4.13.2"
# https://github.com/robfletcher/strikt/releases
strikt = "0.35.1"
# https://github.com/cashapp/turbine/releases
turbine = "1.2.1"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
plugin-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }

# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# https://developer.android.com/jetpack/androidx/releases/arch-core
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-core" }
# https://developer.android.com/jetpack/androidx/releases/fragment
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
# https://developer.android.com/jetpack/androidx/releases/test
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-junit" }

# https://junit.org/junit4/
junit4 = { module = "junit:junit", version.ref = "junit4" }
# https://github.com/robfletcher/strikt
strikt = { module = "io.strikt:strikt-core", version.ref = "strikt" }
# https://github.com/cashapp/turbine
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
